/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author carli
 */
public class controle_atividade extends javax.swing.JFrame {

    /**
     * Creates new form controle_atividade
     */
    public controle_atividade() {
        initComponents();
    }
    
    cadastro_alunos cadastro_alunos = new cadastro_alunos();
    cadastro_professores cadastro_professores = new cadastro_professores();
    cadastro_disciplinas cadastro_disciplinas = new cadastro_disciplinas();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrarAlunos = new javax.swing.JButton();
        jButtonCadastrarProfessores = new javax.swing.JButton();
        jButtonCadastrarDisciplinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Controle de Atividades");

        jButtonCadastrarAlunos.setText("Cadastrar Alunos");
        jButtonCadastrarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarAlunosActionPerformed(evt);
            }
        });

        jButtonCadastrarProfessores.setText("Cadastrar Professores");
        jButtonCadastrarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProfessoresActionPerformed(evt);
            }
        });

        jButtonCadastrarDisciplinas.setText("Cadastrar Disciplinas");
        jButtonCadastrarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarDisciplinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCadastrarDisciplinas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonCadastrarAlunos)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(jButtonCadastrarProfessores))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jButtonCadastrarAlunos)
                .addGap(31, 31, 31)
                .addComponent(jButtonCadastrarProfessores)
                .addGap(43, 43, 43)
                .addComponent(jButtonCadastrarDisciplinas)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarAlunosActionPerformed
        cadastro_alunos.setLocationRelativeTo(null);
        cadastro_alunos.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarAlunosActionPerformed

    private void jButtonCadastrarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProfessoresActionPerformed
        cadastro_professores.setLocationRelativeTo(null);
        cadastro_professores.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarProfessoresActionPerformed

    private void jButtonCadastrarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarDisciplinasActionPerformed
        cadastro_disciplinas.setLocationRelativeTo(null);
        cadastro_disciplinas.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarDisciplinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controle_atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controle_atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controle_atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controle_atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controle_atividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarAlunos;
    private javax.swing.JButton jButtonCadastrarDisciplinas;
    private javax.swing.JButton jButtonCadastrarProfessores;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
